LPGCylinderSystem/Models/Cylinder.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LPGCylinderSystem.Models
{
    public class Cylinder
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Cylinder_Id { get; set; }
        public int Quantity { get; set; }
        public int SubsidyAmount { get; set; }
        public string CylinderType { get; set; }
        public int Price { get; set; }


    }

}

LPGCylinderSystem/Controllers/AdminController.cs
using LPGCylinderSystem.Data.Stores;
using LPGCylinderSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace LPGCylinderSystem.Controllers
{
    [Authorize(Roles="ADMIN")]
    public class AdminController : Controller
    {
    
    
    //just git testing
    //just git testing
    
    
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ClassRepository<ApplicationUser> _classRepository;
        // GET: AdminController
        public AdminController(UserManager<ApplicationUser> userManager, ClassRepository<ApplicationUser> classRepository)
        {
            _userManager = userManager;
            _classRepository = classRepository;
        }
        [HttpGet]
        public ActionResult Cylinder()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CylinderAsync(string cylindertype,Cylinder cylinder, CancellationToken token)
        {
            
                cylinder.Cylinder_Id = ObjectId.GenerateNewId().ToString();
                await _classRepository.CreateCylinderAsync(cylinder, token);
             
            return View();
        }

        public ActionResult Index()
        { 
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
           IEnumerable<ApplicationUser> users= _classRepository.GetuserssAsync();

            int flag= 0;
            foreach(var user in users)
            {
                if (user.Complaints != null)
                {
                    flag = 1;
                    break;
                }
            }
            if (flag == 0)
            {
                ViewData["Error"] = "Error";
                return View();
            }
            else
            {
                
                return View(users);
            }
            
        }

        public ActionResult Deliver(int id)
        {
            IEnumerable<ApplicationUser> users = _classRepository.GetuserssAsync();

            int flag = 0;
            foreach (var user in users)
            {
                if (user.Bookings != null)
                {
                    flag = 1;
                    break;
                }
            }
            if (flag == 0)
            {
                ViewBag.error = "Error";
                return View();
            }
            else
            {
                return View(users);
            }

        }

        public ActionResult Assign(string id,string uid)
        {
            IEnumerable<ApplicationUser> users = _classRepository.GetuserssAsync();
            
            List<ApplicationUser> us = new List<ApplicationUser>();
            foreach (var user in users)
            {
                if(user.IsDeliveryBoy==true)
                {
                    us.Add(user);
                }
            }
            ViewBag.bid = id;
            TempData["uuid"] = uid;

                return View(us);
        }

        public async Task<ActionResult> AssignedAsync(string id,string uid)
        {
            var user = _classRepository.FindByIdAsync(TempData["uuid"].ToString());
            var book = user.Result.Bookings;
            foreach (Booking b in user.Result.Bookings)
            {
                if(b.Booking_Id==id)
                {
                    b.OrderStatus = "Out of Delivery";
                    b.DeliveryBoy_Id = uid;
                    //book.Add(b);
                    break;
                }
            }
            user.Result.Bookings = book;
            await _userManager.UpdateAsync(user.Result);
            return View("Index");
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Netbanking netbanking, CancellationToken token)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var netbankingg = new Netbanking
                    {
                        _id=ObjectId.GenerateNewId().ToString(),
                        Username = netbanking.Username,
                        Password=netbanking.Password,
                        balance=netbanking.balance,
                        Bank=netbanking.Bank
                    };
                    await _classRepository.CreateNetbankingAsync(netbanking,token);
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    return  View();
                }
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CreateCard()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCard(Dcard card, CancellationToken token)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var cardd = new Dcard
                    {
                        _id = ObjectId.GenerateNewId().ToString(),
                       CardNumber=card.CardNumber,
                        balance = card.balance,
                        month=card.month,
                        year=card.year,
                        CVV=card.CVV,mailid=card.mailid
                  
                    };
                    await _classRepository.CreateCardAsync(cardd, token);
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LPGCylinderSystem/Controllers/ComplaintController.cs
using LPGCylinderSystem.Data.Stores;
using LPGCylinderSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace LPGCylinderSystem.Controllers
{
    [Authorize]
    public class ComplaintController : Controller
    {
        // GET: ComplaintController
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ClassRepository<ApplicationUser> _classRepository;
        // GET: AdminController
        public ComplaintController(ClassRepository<ApplicationUser> classRepository, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _classRepository = classRepository;
        }
        [HttpGet]
        public ActionResult Index(String  id)
        {
           
            String Booking_id = id;
            ViewData["Booking_id"] = Booking_id;
            return View();
        }

        
        public async Task<ActionResult> DetailsAsync(Complaint complaint, IFormCollection collection, CancellationToken token)
        {
            complaint.Complaint_Id = ObjectId.GenerateNewId().ToString();
            complaint.Status = "pending";
            
            //complaint.Booking_Id = collection["Booking_Id"];
          //  await _classRepository.CreateComplaintAsync(complaint, token);
            var user1 = _userManager.FindByNameAsync(User.Identity.Name.ToUpper());
            var complaints = user1.Result.Complaints;
            if (complaint.Booking_Id == null && complaints == null)
            {
                ViewData["Error"] = "Error";
                return View();
            }
            if(complaint.Booking_Id == null)
            {
                return View(complaints);
            }
            if (complaints == null)
            {
                complaints = new List<Complaint>();
                complaints.Add(complaint);
                user1.Result.Complaints = complaints;
                await _userManager.UpdateAsync(user1.Result);
                return View(complaints);
            }
            else
            {
                complaints.Add(complaint);
                user1.Result.Complaints = complaints;
                await _userManager.UpdateAsync(user1.Result);
                return View(complaints);
            }

            
        }

        // GET: ComplaintController/Create
        //[HttpGet("{id}/{uid}")]
        [HttpGet]
        public ActionResult Resolve(String id,String uid)
        {

            TempData["uid"] = uid;
           var user= _classRepository.FindByIdAsync(uid);

            //var user =await  _classRepository.FindByComplainIdAsync(id);
            foreach (var com in user.Result.Complaints)
            {
                if (com.Complaint_Id == id)
                {
                    if (com.Status == "pending")
                    {
                        return View(com);
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> ResolveAsync(Complaint complaint,String Booking_Id,String Complaint_Id,String Status)
        {
            var user = _classRepository.FindByIdAsync(TempData["uid"].ToString());
            var complaints = user.Result.Complaints;
            List<Complaint> comp = new List<Complaint>();
            foreach(var com in complaints)
            {
                if (com.Complaint_Id == Complaint_Id)
                {
                    com.Status = "Response";
                    com.Remark = complaint.Remark;
                   
                }
                comp.Add(com);
            }
            user.Result.Complaints = comp;
           await _userManager.UpdateAsync(user.Result);
            return RedirectToAction( "Index", "Admin");
        }

        [HttpGet]
        public ActionResult Resolved(String id)
        {
            var user1 = _userManager.FindByNameAsync(User.Identity.Name.ToUpper());
           List<Complaint> complaints= user1.Result.Complaints.FindAll(x => x.Booking_Id == id);
           List<Complaint> com = new List<Complaint>();
            foreach(var complaint in complaints)
            {
                if (complaint.Status == "Response")
                {
                    com.Add(complaint);           
                }
            }
            return View(com);

        }


            // POST: ComplaintController/Create
            [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



    }
}

LPGCylinderSystem/Views/Admin/Assign.cshtml
@model List<LPGCylinderSystem.Models.ApplicationUser>

@{
    ViewData["Title"] = "Assign";
}

<h1>Assign Delivery Boys</h1>

<form runat="server">
    <h4>Delivery Boys</h4>
    @foreach (ApplicationUser user in Model)
    {
        <div>




            <hr />
            <dl class="row">

                <dt>
                    Mobile Number:
                </dt>
                <dd class="col-sm-10">
                    @user.MobileNo
                </dd>
                <dt>
                    DeliveryBoy ID:
                </dt>
                <dd class="col-sm-10">
                    @user.Id
                </dd>
                <dt>
                    DeliveryBoy Name:
                </dt>
                <dd class="col-sm-10">
                    @user.Name
                </dd>

            </dl>
        </div>
        <div>
            <button class="btn btn-dark" name="uid" value="@user.Id.ToString()"  asp-controller="Admin" asp-action="Assigned" asp-route-id="@ViewBag.bid"> Assign Now </button>
            <a asp-action="Deliver" asp-controller="Admin">Back to List</a>
        </div>
    }
</form>

LPGCylinderSystem/Views/Admin/Create.cshtml
@model LPGCylinderSystem.Models.Netbanking

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Netbanking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Netbanking_ID" class="control-label"></label>
                <input asp-for="Netbanking_ID" class="form-control" />
                <span asp-validation-for="Netbanking_ID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"  ></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="balance" class="control-label"></label>
                <input asp-for="balance" class="form-control" />
                <span asp-validation-for="balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bank" class="control-label"></label>
                <input asp-for="Bank" class="form-control" />
                <span asp-validation-for="Bank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LPGCylinderSystem/Views/Admin/CreateCard.cshtml
@model LPGCylinderSystem.Models.Dcard

@{
    ViewData["Title"] = "CreateCard";
}

<h1>CreateCard</h1>

<h4>Dcard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCard">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Card_Id" class="control-label"></label>
                <input asp-for="Card_Id" class="form-control" />
                <span asp-validation-for="Card_Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="month" class="control-label"></label>
                <input asp-for="month" class="form-control" />
                <span asp-validation-for="month" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CVV" class="control-label"></label>
                <input asp-for="CVV" class="form-control" />
                <span asp-validation-for="CVV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mailid" class="control-label"></label>
                <input asp-for="mailid" class="form-control" />
                <span asp-validation-for="mailid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="balance" class="control-label"></label>
                <input asp-for="balance" class="form-control" />
                <span asp-validation-for="balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LPGCylinderSystem/Views/Admin/Cylinder.cshtml
@model LPGCylinderSystem.Models.Cylinder

@{
    ViewData["Title"] = "Cylinder";
    
}

<head runat="server">
    <title></title>
    <script src="jquery-3.1.0.js"></script>
    <script>
        $(document).ready(function () {
            $('#selectnumber').change(function () {
                var id = $('#selectnumber option:selected').text();
                ViewBag.type = id;     
            })
        });
    </script>
</head>
<h1>Cylinder</h1>

<h4>Cylinder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cylinder">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CylinderType" class="control-label"></label>
                <select name="cylindertype" class="form-control form-control-lg" id="selectnumber">
                    <option value="14.2 Kg">14.2 Kg</option>
                    <option value="2.5 Kg">2.5 Kg</option>
                    <option value="20 Kg">20 Kg</option>
                </select>
                <span asp-validation-for="CylinderType" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="SubsidyAmount" class="control-label"></label>
                <input asp-for="SubsidyAmount" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LPGCylinderSystem/Views/Admin/Deliver.cshtml
@model IEnumerable<LPGCylinderSystem.Models.ApplicationUser>

@{ ViewData["Title"] = "Details"; }






@if (ViewBag.error == "Error")
{
    <h1>No Pending Orders</h1> 
}
else
{
      <form runat="server">



            @foreach (var user in Model)
            {
               
                @if (user.Bookings != null)
                {
                    <div>
                    <hr />
                    <dl class="row">



                        @foreach (LPGCylinderSystem.Models.Booking booking in user.Bookings)
                        {
                    @if ((booking.OrderStatus == "Confirmed" || booking.OrderStatus == "Confirmed-Payment Received") && booking.DeliveryBoy_Id == null)
                    {
                    <dt class="col-sm-2">
                        User Mobile
                    </dt>
                                                    <dd class="col-sm-10">
                                                        @user.MobileNo
                                                    </dd>
                                                                                    <dt class="col-sm-2">
                                                                                        User Email
                                                                                    </dt>
                                                                                                                    <dd class="col-sm-10">
                                                                                                                        @user.Email
                                                                                                                    </dd>


                                                                                                                                                    <dt class="col-sm-2">
                                                                                                                                                        Booking_Id
                                                                                                                                                    </dt>
                                                                                                                                                                                    <dd class="col-sm-10">
                                                                                                                                                                                        @booking.Booking_Id
                                                                                                                                                                                    </dd>

                                                                                                                                                                                                                    <dt class="col-sm-2">
                                                                                                                                                                                                                        Payment Method
                                                                                                                                                                                                                    </dt>
                                                                                                                                                                                                                                                    <dd class="col-sm-10">
                                                                                                                                                                                                                                                        @booking.PaymentMethod
                                                                                                                                                                                                                                                    </dd>
                                                                                                                                                                                                                                                                                   

                                                                                                                                                                                                                                                                                                                                                    <dt class="col-12">

                                                                                                                                                                                                                                                                                                                                                        <button class="btn btn-dark" name="uid" value="@user.Id.ToString()" asp-controller="Admin" asp-action="Assign" asp-route-id="@booking.Booking_Id"> Assign Delivery Agent </button>
                                                                                                                                                                                                                                                                                                                                                        @*<input type="hidden" name="uid" asp-for="@user.Id.ToString()" />*@
                                                                                                                                                                                                                                                                                                                                                    </dt>
//asp - route - uid = "@user.Id.ToString()"


                                                                                                                                                                                                                                                                                                                                                }}
                    </dl>
                        </div>
                }
            }





                    <h1>@ViewBag.test</h1>
</form>
}

LPGCylinderSystem/Views/Admin/Details.cshtml
@model IEnumerable<LPGCylinderSystem.Models.ApplicationUser>

@{
    ViewData["Title"] = "Details";

}






@if (ViewBag.Error == "Error")
{
    <h1>No Complaints yet!!!!</h1>
}
else
{
    <form runat="server">



        @foreach (var user in Model)
        {
            int temp = 0;
            @if (user.Complaints != null)
            {
            <div>
                <hr />
                <dl class="row">

                    

                    @foreach (Complaint complaint in user.Complaints)
                    {
                        @if (complaint.Status == "pending")
                        {
                            temp = 1;
                            <dt class="col-sm-2">
                                Booking_Id
                            </dt>
                            <dd class="col-sm-10">
                                @complaint.Booking_Id
                            </dd>

                            <dt class="col-sm-2">
                                Complaint_Id
                            </dt>
                            <dd class="col-sm-10">
                                @complaint.Complaint_Id
                            </dd>

                            <dt class="col-sm-2">
                                Category
                            </dt>
                            <dd class="col-sm-10">
                                @complaint.Category
                            </dd>

                            <dt class="col-sm-2">
                                Description
                            </dt>
                            <dd class="col-sm-10">
                                @complaint.Description
                            </dd>
                            <dt class="col-12">

                                <button class="btn btn-dark" name="uid" value="@user.Id.ToString()" asp-controller="Complaint" asp-action="Resolve" asp-route-id="@complaint.Complaint_Id"> Resolve </button>
                                @*<input type="hidden" name="uid" asp-for="@user.Id.ToString()" />*@
                            </dt>
                            //asp - route - uid = "@user.Id.ToString()"


                        }






                    }

                    @if (temp == 1)
                    {



                        <dt class="col-sm-2">
                            userid
                        </dt>
                        <dd class="col-sm-10">
                            @user.Id
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(user => user.Connection_Id)
                        </dt>
                        <dd class="col-sm-10">
                            @user.Connection_Id
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(user => user.Agency_Id)
                        </dt>
                        <dd class="col-sm-10">
                            @user.Agency_Id
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(user => user.UserName)
                        </dt>
                        <dd class="col-sm-10">
                            @user.UserName
                        </dd>

                    }

                </dl>


            </div>
            <hr />
            <hr />
            }



        <h1>@ViewBag.test</h1>
        }
    </form>
}

LPGCylinderSystem/Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="row">
    <div class="col-sm-4">

        <a class="btn btn-dark" asp-area="" asp-controller="Admin" asp-action="Create">Netbanking</a>


    </div>
    <div class="col-sm-4">
        <a class="btn btn-dark" asp-area="" asp-controller="Admin" asp-action="CreateCard">Card</a>

    </div>
    <div class="col-sm-4">
        <a class="btn btn-dark" asp-area="" asp-controller="Admin" asp-action="Details">Complaints</a>
    </div>
    <div class="col-sm-4">
        <a class="btn btn-dark" asp-area="" asp-controller="Admin" asp-action="Deliver">Pending Deliveries</a>
    </div>
    <div class="col-sm-4">
        <a class="btn btn-dark" asp-area="" asp-controller="Admin" asp-action="Cylinder">Add Cylinder</a>
    </div>
</div>